# Generated by Django 2.1.7 on 2019-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
