# Generated by Django 2.1.7 on 2019-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190716_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='★', max_length=6),
        ),
    ]
