# Generated by Django 2.1.7 on 2019-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='star',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], max_length=6),
        ),
    ]
